"""Emit a runnable Nextflow project from a resolved Chain.

Each nf-core pipeline becomes one process in a driver workflow that shells out
to `nextflow run nf-core/<name> -r <rev>`. Nextflow's own DSL2 `include` can
only pull in modules and subworkflows from the local project, not whole remote
pipelines, so a nested run is the honest way to compose released pipelines
without vendoring their source.

Literal params are written to a per-step JSON params file (which VSCode
validates against the pipeline's fetched schema); chained inputs are passed on
the command line, because only Nextflow knows their staged paths at runtime.
"""

from __future__ import annotations

import json
import os
import platform
import subprocess
from pathlib import Path

from .graph import Chain, ResolvedStep


def _local_resources() -> tuple[int, int]:
    """(cpus, memory_gb) to cap nested runs to, so a pipeline that requests more
    than this machine has can still be scheduled locally.

    nf-core processes routinely request 36 GB+; on a laptop Nextflow refuses to
    run them ("requirement exceeds available memory"). Capping to the machine's
    own resources fixes that. Memory leaves ~6 GB for the OS/JVM/Docker.
    """
    cpus = os.cpu_count() or 4
    total_gb = 8
    try:
        if platform.system() == "Darwin":
            out = subprocess.run(["sysctl", "-n", "hw.memsize"], capture_output=True, text=True)
            total_gb = int(out.stdout.strip()) // (1024**3)
        elif platform.system() == "Linux":
            for line in Path("/proc/meminfo").read_text().splitlines():
                if line.startswith("MemTotal:"):
                    total_gb = int(line.split()[1]) // (1024**2)
                    break
    except (OSError, ValueError):
        pass
    return cpus, max(4, total_gb - 6)


def render_local_config(cpus: int, mem_gb: int) -> str:
    return f"""{BANNER}
// Caps every process to this machine's resources, so a pipeline that requests
// more than you have (nf-core routinely asks for 36 GB+) still schedules.
// Delete this / drop the `-c` for it on a big machine or a cloud executor.
process {{
    resourceLimits = [ cpus: {cpus}, memory: {mem_gb}.GB, time: 24.h ]
}}
"""

BANNER = "// GENERATED BY nf-chain — do not edit. Regenerate with `nfchain build`."

# Config parser each nested pipeline runs under (exported as NXF_SYNTAX_PARSER).
# 2024-era nf-core releases put a `def check_max(...)` helper in nextflow.config
# that Nextflow 25+'s default strict parser rejects. `v1` selects the legacy
# parser, which accepts it — so the chain runs on current Nextflow (26.x)
# without downgrading. Set to `v2` once every pipeline in the chain has dropped
# check_max.
DEFAULT_SYNTAX_PARSER = "v1"


def _params_file(step: ResolvedStep) -> dict:
    params = dict(step.params)
    params["outdir"] = step.var  # each step publishes into its own subdirectory
    return params


def _process(step: ResolvedStep, consumed: set[str]) -> str:
    ref = step.ref
    inputs = ["    path params_file"]
    cli: list[str] = []

    if step.accession_input is not None:
        inputs.append("    path accessions")
        cli.append("--input ${accessions}")

    for wire in sorted(step.wires, key=lambda w: w.param):
        inputs.append(f"    path in_{wire.param}")
        cli.append(f"--{wire.param} ${{in_{wire.param}}}")

    outputs = [f'    path "{step.var}", emit: outdir']
    for art in _emitted(step):
        opt = "" if art.name in consumed else ", optional: true"
        outputs.append(f'    path "{step.var}/{art.path}", emit: {art.name}{opt}')

    # Nextflow's own options (`-x`) come first; the nested pipeline's params
    # (`--x`) come last. `\\` survives Groovy's string escaping as the shell's
    # line continuation.
    core = [
        f"nextflow run {ref.full_name}",
        f"-r {ref.revision}",
        "-profile ${params.nf_profile}",
        "-c ${projectDir}/local.config",
        "-params-file ${params_file}",
        "-ansi-log false",
        "-work-dir ./work",
    ]
    run = " \\\\\n        ".join(core + cli)
    # Select the config parser for the nested pipeline. A current Nextflow
    # (26.x) defaults to a strict parser that rejects the `def check_max(...)`
    # helper 2024-era nf-core releases ship in nextflow.config; `v1` accepts it.
    # Set on the launch env because NXF_SYNTAX_PARSER is read at config-parse
    # time — works with any `nextflow` on PATH, Homebrew's fixed build included.
    # The `?: 'v1'` fallback means a missing param renders `v1`, never `null`
    # (an empty value is rejected with "Invalid NXF_SYNTAX_PARSER setting").
    body = (
        f"    export NXF_SYNTAX_PARSER=${{params.nf_syntax_parser ?: '{DEFAULT_SYNTAX_PARSER}'}}"
        f"\n    {run}"
    )
    return f'''process {step.process} {{
    tag "{ref.full_name}@{ref.revision}"
    publishDir params.outdir, mode: 'copy'
    // Surface the nested pipeline's own task log (some Nextflow console
    // renderers only flush it on completion, so for guaranteed live per-task
    // output prefer run.sh). Without this the step is a silent "0 of 1" spinner.
    debug true

    input:
{chr(10).join(inputs)}

    output:
{chr(10).join(outputs)}

    script:
    """
{body}
    """

    stub:
    """
{_stub_body(step)}
    """
}}'''


def _stub_path(step_var: str, art_path: str) -> str:
    """Turn a declared output glob into one concrete path a stub can create."""
    concrete = art_path.replace("**", "stub").replace("*", "stub")
    return f"{step_var}/{concrete}"


def _stub_body(step: ResolvedStep) -> str:
    """A `-stub-run` block that materialises every declared output.

    This is what makes a chain testable without running a single real pipeline:
    `nextflow run ... -stub-run` executes the whole DAG in seconds, and any
    broken wire fails loudly because a consumed output won't exist.
    """
    files = [_stub_path(step.var, art.path) for art in _emitted(step)]
    lines = [f"mkdir -p {step.var}"]
    dirs = sorted({f.rsplit("/", 1)[0] for f in files if "/" in f})
    for d in dirs:
        lines.append(f"mkdir -p {d}")
    for f in files:
        lines.append(f"touch {f}")
    return "\n".join(f"    {ln}" for ln in lines)


def _emitted(step: ResolvedStep):
    from . import contracts

    return contracts.emits(step.name)


def _consumed_artifacts(chain: Chain) -> dict[str, set[str]]:
    """artifact names actually read downstream, per producing step."""
    consumed: dict[str, set[str]] = {s.var: set() for s in chain.steps}
    for step in chain.steps:
        for wire in step.wires:
            consumed[wire.source_step].add(wire.artifact.name)
    return consumed


def _workflow(chain: Chain) -> str:
    lines = ["workflow {"]

    for step in chain.steps:
        if step.accession_input is not None:
            ids = ", ".join(f"'{i}'" for i in step.accession_input)
            lines.append(
                f"    ch_{step.var}_ids = Channel.of( {ids} )"
                f".collectFile( name: '{step.var}.accessions.csv', newLine: true )"
            )

    lines.append("")
    for step in chain.steps:
        args = [f'file("${{projectDir}}/params/{step.var}.json")']
        if step.accession_input is not None:
            args.append(f"ch_{step.var}_ids")
        for wire in sorted(step.wires, key=lambda w: w.param):
            args.append(f"{wire.source_step}.{wire.artifact.name}")
        lines.append(f"    {step.var} = {step.process}( {', '.join(args)} )")

    lines.append("}")
    return "\n".join(lines)


def _config(chain: Chain) -> str:
    steps = ", ".join(f"{s.var}=nf-core/{s.name}@{s.ref.revision}" for s in chain.steps)
    return f"""{BANNER}
// chain: {steps}

params {{
    outdir     = 'results'
    // Forwarded to every nested pipeline as `-profile`; a profile below sets it.
    nf_profile = 'docker'
    // Config parser for nested runs (exported as NXF_SYNTAX_PARSER). Current
    // Nextflow rejects the `def check_max(...)` in 2024-era nf-core configs;
    // `v1` is the legacy parser that accepts it. Override: `--nf_syntax_parser v2`.
    nf_syntax_parser = '{DEFAULT_SYNTAX_PARSER}'
}}

process {{
    // The driver processes only orchestrate; the nested runs do the real work
    // and request their own resources from the executor.
    executor = 'local'
    cpus     = 1
    memory   = '2 GB'
}}

// `-profile X` on the driver selects the profile handed to the *nested* runs.
// The driver itself stays local — it only shells out to `nextflow run`.
profiles {{
    docker      {{ params.nf_profile = 'docker' }}
    singularity {{ params.nf_profile = 'singularity' }}
    conda       {{ params.nf_profile = 'conda' }}
    podman      {{ params.nf_profile = 'podman' }}
    test        {{ params.nf_profile = 'test,docker' }}
    standard    {{ params.nf_profile = 'docker' }}
}}
"""


def render_main(chain: Chain) -> str:
    consumed = _consumed_artifacts(chain)
    parts = [
        "#!/usr/bin/env nextflow",
        BANNER,
        f"// source: {chain.flow.path}",
        "",
        "nextflow.enable.dsl = 2",
        "",
    ]
    for step in chain.steps:
        parts.append(_process(step, consumed[step.var]))
        parts.append("")
    parts.append(_workflow(chain))
    parts.append("")
    return "\n".join(parts)


def accessions_filename(step: ResolvedStep) -> str:
    return f"{step.var}.accessions.csv"


def render_run_sh(chain: Chain) -> str:
    """A sequential runner: each pipeline is a top-level `nextflow run`.

    Unlike main.nf (which nests each pipeline inside a driver process and so
    hides the nested tasks behind a single spinner), this runs the pipelines one
    after another as ordinary runs — you see every task of every pipeline live,
    exactly like running nf-core by hand. Outputs are wired by passing each
    step's published path as the next step's input.
    """
    lines = [
        "#!/usr/bin/env bash",
        "# " + BANNER.lstrip("/ "),
        "# Sequential chain runner — full live task output for every pipeline.",
        "#   ./run.sh [profile] [extra nextflow args...]",
        "# e.g. ./run.sh docker -with-tower       (one Seqera run per pipeline;",
        "#      needs TOWER_ACCESS_TOKEN in the environment)",
        "set -euo pipefail",
        "",
        'HERE="$(cd "$(dirname "$0")" && pwd)"',
        'PROFILE="${1:-docker}"',
        "shift || true",
        "# Args after the profile are forwarded verbatim to each pipeline launch",
        "# (e.g. -with-tower, -with-report, -resume, -c my.config).",
        'EXTRA=("$@")',
        'OUTDIR="$HERE/results"',
        "# Shared run tag: every step of THIS invocation is named <TAG>_<step>, so",
        "# the runs are linkable in `nextflow log` and the logs. Override with",
        "# NFCHAIN_TAG=myexp ./run.sh ...  (must start with a letter).",
        'TAG="${NFCHAIN_TAG:-run_$(date +%Y%m%d_%H%M%S)}"',
        "# Legacy config parser: accepts the check_max() in 2024-era nf-core configs.",
        'export NXF_SYNTAX_PARSER="${NXF_SYNTAX_PARSER:-v1}"',
        'echo "run tag: $TAG   (steps: ' + ", ".join(f"{s.var}=${{TAG}}_{s.var}" for s in chain.steps) + ')"',
        "",
        "# Run from a clean dir so Nextflow does NOT auto-load the driver's",
        "# nextflow.config (that config is for main.nf; loading it here would",
        "# inject nf_profile/nf_syntax_parser as bogus params into each pipeline).",
        'mkdir -p "$HERE/run" && cd "$HERE/run"',
        "",
    ]
    for i, step in enumerate(chain.steps, 1):
        ref = step.ref
        inp = None
        if step.accession_input is not None:
            inp = f'"$HERE/params/{accessions_filename(step)}"'
        else:
            for wire in step.wires:
                if wire.param == "input":
                    inp = f'"$OUTDIR/{wire.source_step}/{wire.artifact.path}"'
        cmd = [
            "nextflow run " + ref.full_name,
            "-r " + ref.revision,
            f'-name "${{TAG}}_{step.var}"',  # linkable run name, shared TAG per chain
            '-profile "$PROFILE"',
            '-c "$HERE/local.config"',  # cap resources to this machine
            f'-params-file "$HERE/params/{step.var}.json"',
        ]
        if inp is not None:
            cmd.append(f"--input {inp}")
        cmd.append(f'--outdir "$OUTDIR/{step.var}"')
        cmd.append("-resume")
        # Safe even when EXTRA is empty under `set -u` on bash 3.2 (macOS).
        cmd.append('"${EXTRA[@]+"${EXTRA[@]}"}"')
        joined = " \\\n        ".join(cmd)
        lines.append(f'echo "==> step {i}/{len(chain.steps)}: {ref.full_name}@{ref.revision}"')
        lines.append(f"    {joined}")
        lines.append("")
    # Linked summary: run names ↔ output locations, and how to see them together.
    lines.append('echo ""')
    lines.append('echo "chain complete (tag: $TAG)"')
    for step in chain.steps:
        lines.append(
            f'echo "  {step.var:<8} run=${{TAG}}_{step.var}   outdir=$OUTDIR/{step.var}"'
        )
    lines.append('echo "  work dir: $HERE/run/work"')
    lines.append('echo "  see all runs linked:  (cd \\"$HERE/run\\" && nextflow log)"')
    return "\n".join(lines) + "\n"


# Boolean params that make a stub run light by skipping the heavy real work a
# module would otherwise do (a `-stub-run` still executes modules that lack a
# stub: block). Set when the pipeline's schema actually declares them.
STUB_LIGHTENERS = ("skip_fastq_download",)


def render_stubs_sh(chain: Chain) -> str:
    """Stub-run each pipeline on its own to list its individual tasks.

    `-stub-run` replaces a process with its `stub:` block *only if it has one*;
    modules without a stub run for real. To keep that from downloading, we also
    set any download-skipping param the pipeline's schema declares (e.g.
    fetchngs' `skip_fastq_download`). It uses each pipeline's own `test` data, so
    it's a task-graph preview, not a data run.
    """
    lines = [
        "#!/usr/bin/env bash",
        "# " + BANNER.lstrip("/ "),
        "# Per-pipeline stub run — list each pipeline's tasks, kept light.",
        "#   ./stubs.sh [profile]   (default: test,docker)",
        "set -uo pipefail",  # no -e: one pipeline erroring must not stop the rest
        "",
        'HERE="$(cd "$(dirname "$0")" && pwd)"',
        'PROFILE="${1:-test,docker}"',
        'export NXF_SYNTAX_PARSER="${NXF_SYNTAX_PARSER:-v1}"',
        'mkdir -p "$HERE/stubs" && cd "$HERE/stubs"',
        "",
    ]
    for i, step in enumerate(chain.steps, 1):
        ref = step.ref
        light = [p for p in STUB_LIGHTENERS if p in step.sch.params]
        cmd = [
            "nextflow run " + ref.full_name,
            "-r " + ref.revision,
            '-profile "$PROFILE"',
            "-stub-run",
            f'--outdir "stub_{step.var}"',
        ]
        for p in light:
            cmd.append(f"--{p} true")
        note = f"  (light: --{' --'.join(light)} true)" if light else ""
        lines.append(
            f'echo "==> step {i}/{len(chain.steps)}: {ref.full_name}@{ref.revision}{note}"'
        )
        lines.append("    " + " \\\n        ".join(cmd) + " || true")
        lines.append("")
    lines.append('echo "stub preview complete"')
    return "\n".join(lines) + "\n"


def render_tw_sh(chain: Chain) -> str:
    """Launch the chain on Seqera Platform: one `tw launch` per pipeline, wired
    by S3 paths.

    Seqera runs one pipeline per launch, so a chain is N launches; each step's
    `--outdir` is an S3 path and the next step's `--input` is the previous
    outdir + its published path. Resources come from the compute environment
    (spot or on-demand) — the laptop cap (local.config) is NOT used here.
    """
    lines = [
        "#!/usr/bin/env bash",
        "# " + BANNER.lstrip("/ "),
        "# Launch this chain on Seqera Platform (one run per pipeline, wired by S3).",
        "# Requires the `tw` CLI, and in your environment:",
        "#   TOWER_ACCESS_TOKEN   your Seqera token",
        "#   TW_COMPUTE_ENV       compute-environment name (its work dir + spot/on-demand",
        "#                        are configured there, not here)",
        "#   TW_OUTDIR            S3 results base, e.g. s3://my-bucket/results",
        "#   TW_WORKSPACE         (optional) workspace name/id",
        "# Uploading the accession list to S3 needs the aws CLI.",
        "set -euo pipefail",
        'HERE="$(cd "$(dirname "$0")" && pwd)"',
        ': "${TOWER_ACCESS_TOKEN:?set TOWER_ACCESS_TOKEN}"',
        ': "${TW_COMPUTE_ENV:?set TW_COMPUTE_ENV to your Seqera compute environment}"',
        ': "${TW_OUTDIR:?set TW_OUTDIR to an S3 results base, e.g. s3://bucket/results}"',
        'WS=(); [ -n "${TW_WORKSPACE:-}" ] && WS=(--workspace="$TW_WORKSPACE")',
        "",
        "# merge params/<step>.json with the S3 outdir/input into a launch params file",
        "mkparams() {  # <static.json> <overrides-json> <out.json>",
        "    python3 - \"$@\" <<'PY'",
        "import json,sys",
        "d=json.load(open(sys.argv[1])); d.update(json.loads(sys.argv[2]))",
        "json.dump(d, open(sys.argv[3],'w'), indent=2)",
        "PY",
        "}",
        "",
    ]
    for i, step in enumerate(chain.steps, 1):
        ref = step.ref
        pf = f'"$HERE/params/{step.var}.json"'
        launch_pf = f'"$HERE/params/{step.var}.tw.json"'
        # escaped JSON inside a DOUBLE-quoted shell string, so $TW_OUTDIR expands
        overrides: list[str] = [f'\\"outdir\\":\\"$TW_OUTDIR/{step.var}\\"']

        pre = []
        if step.accession_input is not None:
            # the ID file must live where the cloud can read it → upload to S3
            pre.append(
                f'aws s3 cp "$HERE/params/{accessions_filename(step)}" '
                f'"$TW_OUTDIR/{step.var}/ids.csv"'
            )
            overrides.append(f'\\"input\\":\\"$TW_OUTDIR/{step.var}/ids.csv\\"')
        else:
            for wire in step.wires:
                if wire.param == "input":
                    overrides.append(
                        f'\\"input\\":\\"$TW_OUTDIR/{wire.source_step}/{wire.artifact.path}\\"'
                    )

        lines.append(f'echo "==> step {i}/{len(chain.steps)}: {ref.full_name}@{ref.revision}"')
        lines += ["    " + p for p in pre]
        lines.append(
            f'    mkparams {pf} "{{{",".join(overrides)}}}" {launch_pf}'
        )
        lines.append(
            f'    tw launch https://github.com/{ref.full_name} -r {ref.revision} "${{WS[@]}}" \\\n'
            f'        --compute-env="$TW_COMPUTE_ENV" \\\n'
            f'        --name="${{TW_TAG:-chain}}_{step.var}" \\\n'
            f"        --params-file={launch_pf} \\\n"
            f"        --wait=SUCCEEDED"
        )
        lines.append("")
    lines.append('echo "chain complete → $TW_OUTDIR"')
    return "\n".join(lines) + "\n"


def write(chain: Chain, outdir: Path) -> list[Path]:
    """Write main.nf, run.sh, nextflow.config and params/*. Returns written paths."""
    outdir.mkdir(parents=True, exist_ok=True)
    (outdir / "params").mkdir(exist_ok=True)

    written = []

    main = outdir / "main.nf"
    main.write_text(render_main(chain))
    written.append(main)

    run_sh = outdir / "run.sh"
    run_sh.write_text(render_run_sh(chain))
    run_sh.chmod(0o755)
    written.append(run_sh)

    stubs_sh = outdir / "stubs.sh"
    stubs_sh.write_text(render_stubs_sh(chain))
    stubs_sh.chmod(0o755)
    written.append(stubs_sh)

    tw_sh = outdir / "run.tw.sh"
    tw_sh.write_text(render_tw_sh(chain))
    tw_sh.chmod(0o755)
    written.append(tw_sh)

    cfg = outdir / "nextflow.config"
    cfg.write_text(_config(chain))
    written.append(cfg)

    cpus, mem_gb = _local_resources()
    local_cfg = outdir / "local.config"
    local_cfg.write_text(render_local_config(cpus, mem_gb))
    written.append(local_cfg)

    for step in chain.steps:
        p = outdir / "params" / f"{step.var}.json"
        p.write_text(json.dumps(_params_file(step), indent=2) + "\n")
        written.append(p)
        if step.accession_input is not None:
            af = outdir / "params" / accessions_filename(step)
            af.write_text("\n".join(step.accession_input) + "\n")
            written.append(af)

    return written
