"""Emit a runnable Nextflow project from a resolved Chain.

Each nf-core pipeline becomes one process in a driver workflow that shells out
to `nextflow run nf-core/<name> -r <rev>`. Nextflow's own DSL2 `include` can
only pull in modules and subworkflows from the local project, not whole remote
pipelines, so a nested run is the honest way to compose released pipelines
without vendoring their source.

Literal params are written to a per-step JSON params file (which VSCode
validates against the pipeline's fetched schema); chained inputs are passed on
the command line, because only Nextflow knows their staged paths at runtime.
"""

from __future__ import annotations

import json
from pathlib import Path

from .graph import Chain, ResolvedStep

BANNER = "// GENERATED BY nf-chain — do not edit. Regenerate with `nfchain build`."

# Config parser each nested pipeline runs under (exported as NXF_SYNTAX_PARSER).
# 2024-era nf-core releases put a `def check_max(...)` helper in nextflow.config
# that Nextflow 25+'s default strict parser rejects. `v1` selects the legacy
# parser, which accepts it — so the chain runs on current Nextflow (26.x)
# without downgrading. Set to `v2` once every pipeline in the chain has dropped
# check_max.
DEFAULT_SYNTAX_PARSER = "v1"


def _params_file(step: ResolvedStep) -> dict:
    params = dict(step.params)
    params["outdir"] = step.var  # each step publishes into its own subdirectory
    return params


def _process(step: ResolvedStep, consumed: set[str]) -> str:
    ref = step.ref
    inputs = ["    path params_file"]
    cli: list[str] = []

    if step.accession_input is not None:
        inputs.append("    path accessions")
        cli.append("--input ${accessions}")

    for wire in sorted(step.wires, key=lambda w: w.param):
        inputs.append(f"    path in_{wire.param}")
        cli.append(f"--{wire.param} ${{in_{wire.param}}}")

    outputs = [f'    path "{step.var}", emit: outdir']
    for art in _emitted(step):
        opt = "" if art.name in consumed else ", optional: true"
        outputs.append(f'    path "{step.var}/{art.path}", emit: {art.name}{opt}')

    # Nextflow's own options (`-x`) come first; the nested pipeline's params
    # (`--x`) come last. `\\` survives Groovy's string escaping as the shell's
    # line continuation.
    core = [
        f"nextflow run {ref.full_name}",
        f"-r {ref.revision}",
        "-profile ${params.nf_profile}",
        "-params-file ${params_file}",
        "-ansi-log false",
        "-work-dir ./work",
    ]
    run = " \\\\\n        ".join(core + cli)
    # Select the config parser for the nested pipeline. A current Nextflow
    # (26.x) defaults to a strict parser that rejects the `def check_max(...)`
    # helper 2024-era nf-core releases ship in nextflow.config; `v1` accepts it.
    # Set on the launch env because NXF_SYNTAX_PARSER is read at config-parse
    # time — works with any `nextflow` on PATH, Homebrew's fixed build included.
    body = f"    export NXF_SYNTAX_PARSER=${{params.nf_syntax_parser}}\n    {run}"
    return f'''process {step.process} {{
    tag "{ref.full_name}@{ref.revision}"
    publishDir params.outdir, mode: 'copy'

    input:
{chr(10).join(inputs)}

    output:
{chr(10).join(outputs)}

    script:
    """
{body}
    """

    stub:
    """
{_stub_body(step)}
    """
}}'''


def _stub_path(step_var: str, art_path: str) -> str:
    """Turn a declared output glob into one concrete path a stub can create."""
    concrete = art_path.replace("**", "stub").replace("*", "stub")
    return f"{step_var}/{concrete}"


def _stub_body(step: ResolvedStep) -> str:
    """A `-stub-run` block that materialises every declared output.

    This is what makes a chain testable without running a single real pipeline:
    `nextflow run ... -stub-run` executes the whole DAG in seconds, and any
    broken wire fails loudly because a consumed output won't exist.
    """
    files = [_stub_path(step.var, art.path) for art in _emitted(step)]
    lines = [f"mkdir -p {step.var}"]
    dirs = sorted({f.rsplit("/", 1)[0] for f in files if "/" in f})
    for d in dirs:
        lines.append(f"mkdir -p {d}")
    for f in files:
        lines.append(f"touch {f}")
    return "\n".join(f"    {ln}" for ln in lines)


def _emitted(step: ResolvedStep):
    from . import contracts

    return contracts.emits(step.name)


def _consumed_artifacts(chain: Chain) -> dict[str, set[str]]:
    """artifact names actually read downstream, per producing step."""
    consumed: dict[str, set[str]] = {s.var: set() for s in chain.steps}
    for step in chain.steps:
        for wire in step.wires:
            consumed[wire.source_step].add(wire.artifact.name)
    return consumed


def _workflow(chain: Chain) -> str:
    lines = ["workflow {"]

    for step in chain.steps:
        if step.accession_input is not None:
            ids = ", ".join(f"'{i}'" for i in step.accession_input)
            lines.append(
                f"    ch_{step.var}_ids = Channel.of( {ids} )"
                f".collectFile( name: '{step.var}.accessions.csv', newLine: true )"
            )

    lines.append("")
    for step in chain.steps:
        args = [f'file("${{projectDir}}/params/{step.var}.json")']
        if step.accession_input is not None:
            args.append(f"ch_{step.var}_ids")
        for wire in sorted(step.wires, key=lambda w: w.param):
            args.append(f"{wire.source_step}.{wire.artifact.name}")
        lines.append(f"    {step.var} = {step.process}( {', '.join(args)} )")

    lines.append("}")
    return "\n".join(lines)


def _config(chain: Chain) -> str:
    steps = ", ".join(f"{s.var}=nf-core/{s.name}@{s.ref.revision}" for s in chain.steps)
    return f"""{BANNER}
// chain: {steps}

params {{
    outdir     = 'results'
    // Forwarded to every nested pipeline as `-profile`; a profile below sets it.
    nf_profile = 'docker'
    // Config parser for nested runs (exported as NXF_SYNTAX_PARSER). Current
    // Nextflow rejects the `def check_max(...)` in 2024-era nf-core configs;
    // `v1` is the legacy parser that accepts it. Override: `--nf_syntax_parser v2`.
    nf_syntax_parser = '{DEFAULT_SYNTAX_PARSER}'
}}

process {{
    // The driver processes only orchestrate; the nested runs do the real work
    // and request their own resources from the executor.
    executor = 'local'
    cpus     = 1
    memory   = '2 GB'
}}

// `-profile X` on the driver selects the profile handed to the *nested* runs.
// The driver itself stays local — it only shells out to `nextflow run`.
profiles {{
    docker      {{ params.nf_profile = 'docker' }}
    singularity {{ params.nf_profile = 'singularity' }}
    conda       {{ params.nf_profile = 'conda' }}
    podman      {{ params.nf_profile = 'podman' }}
    test        {{ params.nf_profile = 'test,docker' }}
    standard    {{ params.nf_profile = 'docker' }}
}}
"""


def render_main(chain: Chain) -> str:
    consumed = _consumed_artifacts(chain)
    parts = [
        "#!/usr/bin/env nextflow",
        BANNER,
        f"// source: {chain.flow.path}",
        "",
        "nextflow.enable.dsl = 2",
        "",
    ]
    for step in chain.steps:
        parts.append(_process(step, consumed[step.var]))
        parts.append("")
    parts.append(_workflow(chain))
    parts.append("")
    return "\n".join(parts)


def write(chain: Chain, outdir: Path) -> list[Path]:
    """Write main.nf, nextflow.config and params/*.json. Returns written paths."""
    outdir.mkdir(parents=True, exist_ok=True)
    (outdir / "params").mkdir(exist_ok=True)

    written = []

    main = outdir / "main.nf"
    main.write_text(render_main(chain))
    written.append(main)

    cfg = outdir / "nextflow.config"
    cfg.write_text(_config(chain))
    written.append(cfg)

    for step in chain.steps:
        p = outdir / "params" / f"{step.var}.json"
        p.write_text(json.dumps(_params_file(step), indent=2) + "\n")
        written.append(p)

    return written
