"""Turn live pipeline schemas into editor intelligence.

Two artifacts, both regenerated from the pinned schema every `nfchain sync`:

  .nfchain/stubs/nf_core/__init__.pyi   type stubs -> completion + signature help
  .nfchain/schemas/<pipeline>.json      JSON Schema -> validation of params files

This is what makes a pipeline's inputs show up in VSCode the moment you import
it, without nf-chain ever hardcoding what those inputs are.
"""

from __future__ import annotations

import json
import keyword
from pathlib import Path

from . import contracts
from .graph import MANAGED_PARAMS, Chain
from .schema import Param, PipelineSchema

HEADER = '"""GENERATED BY nf-chain — do not edit. Regenerate with `nfchain sync`."""'

_TYPES = {
    "string": "str",
    "boolean": "bool",
    "integer": "int",
    "number": "float",
}


def _py_literal(value) -> str:
    """Render a schema enum value as Python source, not JSON.

    A schema's `false` is Python's `False`; emitting the JSON spelling produces
    an undefined name that `ast.parse` happily accepts and a type checker does
    not.
    """
    if isinstance(value, bool):
        return "True" if value else "False"
    if value is None:
        return "None"
    if isinstance(value, str):
        return json.dumps(value)
    return repr(value)


def _annotation(p: Param, pipeline: str) -> str:
    if p.name == "input" and pipeline in contracts.ACCESSION_INPUT:
        return "str | list[str]"  # accessions, not a path on disk
    if p.enum:
        literals = ", ".join(_py_literal(v) for v in p.enum)
        return f"Literal[{literals}]"
    base = _TYPES.get(p.type, "Any")
    if p.is_path:
        # A chained artifact is an Output attribute, not a str, at author time.
        return f"{base} | _Artifact"
    return base


def _usable(p: Param, aliases: dict[str, str]) -> bool:
    if p.name in MANAGED_PARAMS:
        return False
    name = aliases.get(p.name, p.name)
    return name.isidentifier() and not keyword.iskeyword(name)


def _signature(sch: PipelineSchema, local_name: str) -> str:
    pipeline = sch.ref.name
    # `input` -> `ids`, so the stub advertises the friendly name.
    rev_alias = contracts.display_alias(pipeline)

    params = [p for p in sch.user_params() if _usable(p, rev_alias)]
    required = [p for p in params if p.required]
    optional = [p for p in params if not p.required]

    lines = [f"def {local_name}("]
    lines.append("    *,")
    # Every param carries `= ...`: a required input may be satisfied by
    # auto-wiring from an upstream step, so the type checker must not demand it.
    # Required-ness is surfaced in the docstring and enforced by `nfchain build`.
    for p in required + optional:
        name = rev_alias.get(p.name, p.name)
        lines.append(f"    {name}: {_annotation(p, pipeline)} = ...,")
    lines.append("    rev: str = ...,")
    lines.append(f") -> _{local_name.capitalize()}Out:")

    doc = [f'    """nf-core/{pipeline}@{sch.ref.revision}']
    if sch.description:
        doc += ["", f"    {sch.description}"]
    if required:
        doc += ["", "    Required:"]
        doc += [f"      {rev_alias.get(p.name, p.name)}: {p.description}" for p in required]
    doc.append('    """')
    lines += doc
    lines.append("    ...")
    return "\n".join(lines)


def _output_class(local_name: str, pipeline: str) -> str:
    arts = contracts.emits(pipeline)
    lines = [f"class _{local_name.capitalize()}Out(_Output):"]
    if not arts:
        lines.append("    ...")
        return "\n".join(lines)
    for art in arts:
        lines.append(f"    {art.name}: _Artifact")
        lines.append(f'    """{art.kind} — {pipeline} outdir/{art.path}"""')
    return "\n".join(lines)


def render_stub(chain: Chain) -> str:
    parts = [
        HEADER,
        "",
        "from typing import Any, Literal",
        "",
        "class _Artifact:",
        '    """A file published by an upstream pipeline; pass it to a downstream one."""',
        "    def __fspath__(self) -> str: ...",
        "",
        "class _Output:",
        "    outdir: _Artifact",
        "",
    ]

    seen: set[str] = set()
    for step in chain.steps:
        local = step.step.imported_as
        if local in seen:
            continue
        seen.add(local)
        parts.append(_output_class(local, step.name))
        parts.append("")
        parts.append(_signature(step.sch, local))
        parts.append("")

    return "\n".join(parts)


def render_params_schema(sch: PipelineSchema) -> dict:
    props: dict[str, dict] = {}
    for p in sch.user_params():
        entry: dict = {"description": p.description or p.help_text}
        if p.enum:
            entry["enum"] = list(p.enum)
        else:
            entry["type"] = p.type
        if p.default is not None:
            entry["default"] = p.default
        if p.pattern:
            entry["pattern"] = p.pattern
        props[p.name] = entry

    # `outdir` is written by nf-chain, so it's allowed but not required here.
    props.setdefault("outdir", {"type": "string", "description": "Managed by nf-chain."})

    return {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "title": f"{sch.ref.full_name}@{sch.ref.revision} params",
        "type": "object",
        "properties": props,
        "additionalProperties": False,
    }


def vscode_settings(chain: Chain, build_dir: str) -> dict:
    schemas = []
    for step in chain.steps:
        schemas.append(
            {
                "fileMatch": [f"/{build_dir}/params/{step.var}.json"],
                "url": f"./.nfchain/schemas/{step.name}.params.schema.json",
            }
        )
    return {
        "files.associations": {"*.flow": "python"},
        "python.analysis.stubPath": ".nfchain/stubs",
        "python.analysis.extraPaths": [".nfchain/stubs"],
        "json.schemas": schemas,
    }


def sync(chain: Chain, root: Path, build_dir: str = "build_nf") -> list[Path]:
    written: list[Path] = []

    stub_dir = root / ".nfchain" / "stubs" / "nf_core"
    stub_dir.mkdir(parents=True, exist_ok=True)
    stub = stub_dir / "__init__.pyi"
    stub.write_text(render_stub(chain))
    written.append(stub)

    schema_dir = root / ".nfchain" / "schemas"
    schema_dir.mkdir(parents=True, exist_ok=True)
    for step in chain.steps:
        p = schema_dir / f"{step.name}.params.schema.json"
        p.write_text(json.dumps(render_params_schema(step.sch), indent=2) + "\n")
        written.append(p)

    vs = root / ".vscode"
    vs.mkdir(exist_ok=True)
    settings_path = vs / "settings.json"
    existing: dict = {}
    if settings_path.exists():
        try:
            existing = json.loads(settings_path.read_text())
        except json.JSONDecodeError:
            existing = {}
    existing.update(vscode_settings(chain, build_dir))
    settings_path.write_text(json.dumps(existing, indent=2) + "\n")
    written.append(settings_path)

    return written
